// **************************** VRCHAT AMPLITUDE CACHE **************************** //
export interface $AmplitudeIPSCategoryWeights {
	category: string;
	weight: number;
}

export interface $AmplitudeUserProperties {
	'acceptedTOSVersion': number;
	'accountType': string;
	'avatarPerfMinRatingToDisplay': string;
	'buildType': string;
	'buildVersion': string;
	'currentAvatarAuthorId': string;
	'currentAvatarAuthorName': string;
	'currentAvatarId': string;
	'currentAvatarName': string;
	'currentlyappliedaccessoriesids': [];
	'currentlyappliedtotalaccessoriescount': number;
	'currentlyapplieduniqueaccessoriescount': number;
	'currentWorldId': string;
	'currentWorldName': string;
	'defaultFormatHDR': string;
	'defaultFormatLDR': string;
	'developerType': string;
	'deviceId': string;
	'displayName': string;
	'eyeLidTrackingType': string;
	'eyeLookTrackingType': string;
	'graphicsDeviceName': string;
	'graphicsDeviceVendor': string;
	'graphicsDeviceVersion': string;
	'graphicsMemorySize': number;
	'hudEnabled': boolean;
	'inputMethod': string;
	'inputType': string;
	'inVRMode': boolean;
	'ips_category_weights': [];
	'ips_segment': string;
	'IsNvidiaGeForceNow': boolean;
	'isOnMeteredConnection': boolean;
	'joinedGroupIds': string[];
	'joinedGroupNames': string[];
	'looksowned_count': number;
	'mainThreadPriority': string;
	'micEnabled': boolean;
	'nameplatesEnabled': boolean;
	'numberOfCustomEmoji': number;
	'numberOfFriends': number;
	'numberOfGroups': number;
	'numberOfStickersInGallery': number;
	'numExtraVRTrackers': number;
	'numOpenVRTrackers': number;
	'numOpenXRTrackers': number;
	'numOSCTrackers': number;
	'numTimesDisabledSelfieExpression': number;
	'numTimesEnabledSelfieExpression': number;
	'numTimesRefusedSelfieExpressionPopup': number;
	'numTimesRefusedSelfieExpressionPopupVrcPlus': number;
	'numTimesSelfieExpressionPopupVrcPlusClicked': number;
	'operatingSystem': string;
	'platform': string;
	'processAffinity': number;
	'processAffinityManuallySet': boolean;
	'processorFrequency': number;
	'processorName': string;
	'processPriority': string;
	'publicbetas': string;
	'releasePlatform': string;
	'safetyLevel': number;
	'safetyLevelName': string;
	'setting_AdvancedGraphicsAntialiasing': number;
	'setting_AFKEnabled': boolean;
	'setting_AllowAvatarCopying': boolean;
	'setting_AllowDirectShares': boolean;
	'setting_AllowDiscordFriends': boolean;
	'setting_AllowFocusView': boolean;
	'setting_AllowPedestalShares': boolean;
	'setting_AllowPrints': boolean;
	'setting_AllowSharedConnections': boolean;
	'setting_AllowUntrustedURL': boolean;
	'setting_AndroidMicMode': string;
	'setting_ApplyColorFilterToWorld': boolean;
	'setting_AskToPortal': boolean;
	'setting_AutoWalkEnabled': boolean;
	'setting_AvatarHapticsEnabled': boolean;
	'setting_AvatarPerformanceRatingMinimumToDisplay': string;
	'setting_AvatarsVolume': number;
	'setting_AvatarVolumeEnabled': boolean;
	'setting_BackgroundDebugLogCollection': boolean;
	'setting_BloomIntensity': number;
	'setting_ChatBubbleAboveHeadPosition': string;
	'setting_ChatBubbleAudioEnabled': boolean;
	'setting_ChatBubbleAudioVolume': number;
	'setting_ChatBubbleAutoSend': boolean;
	'setting_ChatBubbleOpacity': number;
	'setting_ChatBubblePositionHeight': number;
	'setting_ChatBubbleProfanityFilter': boolean;
	'setting_ChatBubbleScale': number;
	'setting_ChatBubbleShowOwn': boolean;
	'setting_ChatBubbleTimeout': number;
	'setting_ChatBubbleVisibility': string;
	'setting_ClearCacheOnStart': boolean;
	'setting_ClockVariant': string;
	'setting_ColorFilterIntensity': number;
	'setting_ColorFilterSelection': string;
	'setting_ComfortTurning': boolean;
	'setting_CurrentLanguage': string;
	'setting_DesktopFOV': number;
	'setting_DesktopReticle': boolean;
	'setting_DirectSharingVisibility': string;
	'setting_DisableAvatarCloningOnEnterWorld': boolean;
	'setting_DisableMicButton': boolean;
	'setting_DoubleTapMainMenuSteamVR2': boolean;
	'setting_DPIScaling': number;
	'setting_EarmuffMode': boolean;
	'setting_EarmuffModeAlwaysShowVisualAid': boolean;
	'setting_EarmuffModeAvatars': boolean;
	'setting_EarmuffModeConeValue': number;
	'setting_EarmuffModeFalloff': number;
	'setting_EarmuffModeFollowHead': string;
	'setting_EarmuffModeLockRotation': boolean;
	'setting_EarmuffModeOffsetValue': number;
	'setting_EarmuffModeRadius': number;
	'setting_EarmuffModeReducedVolume': number;
	'setting_EarmuffModeShowIconInNameplate': boolean;
	'setting_FingerGrabSetting': number;
	'setting_FingerHapticSensitivity': number;
	'setting_FingerHapticStrength': number;
	'setting_FingerJumpEnabled': boolean;
	'setting_FingerWalkSetting': number;
	'setting_FPSCapType': string;
	'setting_FpsLimit': number;
	'setting_FPSType': string;
	'setting_GestureBarEnabled': boolean;
	'setting_GraphicsQuality': string;
	'setting_GroupOnNameplate': string;
	'setting_HeaderClickScrollReset': boolean;
	'setting_HideFallbackAvatar': boolean;
	'setting_HideNotificationPhotos': boolean;
	'setting_HomeAccessType': string;
	'setting_HomeRegion': string;
	'setting_HUDAnchor': string;
	'setting_HUDMicOpacity': number;
	'setting_HUDMode': string;
	'setting_HUDOpacity': number;
	'setting_HUDSmoothing': boolean;
	'setting_InputAvatarsUseFingerTracking': boolean;
	'setting_InputExclusiveHandTracking': boolean;
	'setting_InputGhostHands': string;
	'setting_InputHandsMenuOpenMode': string;
	'setting_InputShowPinchUI': boolean;
	'setting_InteractHapticsEnabled': boolean;
	'setting_InvertControllerVerticalLook': boolean;
	'setting_InvertedMouse': boolean;
	'setting_IsBoopingEnabled': boolean;
	'setting_IsEmojiBoopEffectEnabled': boolean;
	'setting_LandscapeFOV': number;
	'setting_LimitParticleSystems': boolean;
	'setting_LocomotionMethod': string;
	'setting_LodQuality': string;
	'setting_LoggingEnabled': string;
	'setting_MainMenuMovementLocked': boolean;
	'setting_MasterVolume': number;
	'setting_MasterVolumeEnabled': boolean;
	'setting_MaximumAvatarDownloadSize': number;
	'setting_MaximumAvatarUncompressedSize': number;
	'setting_MicBehaviorOnJoinMode': string;
	'setting_MicDeviceName': string;
	'setting_MicEnabled': boolean;
	'setting_MicIconVisibility': string;
	'setting_MicLevel': number;
	'setting_MicMode': string;
	'setting_MicToggleVolume': number;
	'setting_MirrorResolution': string;
	'setting_MMFreePlacementEnabled': boolean;
	'setting_MobileAutoHoldEnabled': boolean;
	'setting_MobileInteractionMode': string;
	'setting_MouseSensitivity': number;
	'setting_NameplateFallbackIconVisible': boolean;
	'setting_NameplateMode': string;
	'setting_NameplateOpacity': number;
	'setting_NameplateQMInfo': boolean;
	'setting_NameplateScale': string;
	'setting_NameplateStatusMode': string;
	'setting_NoiseGate': number;
	'setting_NoiseSuppression': boolean;
	'setting_NotificationsServiceEnabled': boolean;
	'setting_OnlyShowFriendJoinLeaveAndPortalNotifications': boolean;
	'setting_ParticlePhysicsQuality': string;
	'setting_PedestalSharingVisibility': string;
	'setting_PersonalMirror.FaceMirrorOpacity': number;
	'setting_PersonalMirror.FaceMirrorOpacityDesktop': number;
	'setting_PersonalMirror.FaceMirrorPosX': number;
	'setting_PersonalMirror.FaceMirrorPosXDesktop': number;
	'setting_PersonalMirror.FaceMirrorPosY': number;
	'setting_PersonalMirror.FaceMirrorPosYDesktop': number;
	'setting_PersonalMirror.FaceMirrorScale': number;
	'setting_PersonalMirror.FaceMirrorScaleDesktop': number;
	'setting_PersonalMirror.FaceMirrorZoom': number;
	'setting_PersonalMirror.FaceMirrorZoomDesktop': number;
	'setting_PersonalMirror.Grabbable': boolean;
	'setting_PersonalMirror.ImmersiveMove': boolean;
	'setting_PersonalMirror.MirrorOpacity': number;
	'setting_PersonalMirror.MirrorScaleX': number;
	'setting_PersonalMirror.MirrorScaleY': number;
	'setting_PersonalMirror.MirrorSnapping': boolean;
	'setting_PersonalMirror.MovementMode': number;
	'setting_PersonalMirror.ShowBorder': boolean;
	'setting_PersonalMirror.ShowCalibrationMirror': boolean;
	'setting_PersonalMirror.ShowEnvironmentInMirror': boolean;
	'setting_PersonalMirror.ShowFaceMirror': boolean;
	'setting_PersonalMirror.ShowFaceMirrorDesktop': boolean;
	'setting_PersonalMirror.ShowRemotePlayerInMirror': boolean;
	'setting_PersonalMirror.ShowUIInMirror': boolean;
	'setting_PersonalSpace': boolean;
	'setting_PixelLightCount': string;
	'setting_PlayNotificationAudio': boolean;
	'setting_PortalModePlacement': string;
	'setting_PortraitFOV': number;
	'setting_PreferredTimezone': string;
	'setting_PrintVisibility': string;
	'setting_PropsVolume': number;
	'setting_PropsVolumeEnabled': boolean;
	'setting_QuickSelectEnabled': boolean;
	'setting_RandomizeDrone': boolean;
	'setting_RandomizeLoadingScreen': boolean;
	'setting_RandomizePortal': boolean;
	'setting_RandomizeWarpEffect': boolean;
	'setting_ReduceAnimations': boolean;
	'setting_SafetyLevel': string;
	'setting_SavedCameraNearClipOverrideMode': string;
	'setting_ScreenBrightness': number;
	'setting_ScreenContrast': number;
	'setting_SecondaryUIEnabled': boolean;
	'setting_SelectedNetworkRegion': string;
	'setting_selfieExpressionEnabled': boolean;
	'setting_ShadowQualityMode': string;
	'setting_ShowCommunityLabs': boolean;
	'setting_ShowCommunityLabsInWorldSearch': boolean;
	'setting_ShowCompatibilityWarnings': boolean;
	'setting_ShowFriendRequests': boolean;
	'setting_ShowGoButtonInLoad': boolean;
	'setting_ShowGroupBadges': boolean;
	'setting_ShowGroupBadgeToOthers': boolean;
	'setting_ShowInvitesNotification': boolean;
	'setting_ShowJoinNotifications': boolean;
	'setting_ShowLeaveNotifications': boolean;
	'setting_ShowPortalNotifications': boolean;
	'setting_ShowQMDebugInfo': boolean;
	'setting_ShowSocialRank': boolean;
	'setting_ShowTooltips': boolean;
	'setting_SimulateBlindness': boolean;
	'setting_SliderSnapping': boolean;
	'setting_StreamerModeEnabled': boolean;
	'setting_TalkDefaultOn': boolean;
	'setting_ThirdPersonRotation': boolean;
	'setting_ThirdPersonView': boolean;
	'setting_ThirdPersonViewDisabledByScrollIn': boolean;
	'setting_ThirdPersonViewDistance': number;
	'setting_ThirdPersonViewHorizontal': number;
	'setting_ThirdPersonViewVertical': number;
	'setting_TimeFormatMode': string;
	'setting_ToggleTalk': boolean;
	'setting_TouchAutoRotateSpeed': number;
	'setting_TouchSensitivity': number;
	'setting_UIHapticsEnabled': boolean;
	'setting_UIVolume': number;
	'setting_UIVolumeEnabled': boolean;
	'setting_UseColorFilter': boolean;
	'setting_UseGenericInstanceNames': boolean;
	'setting_UseImpostorAsFallback': boolean;
	'setting_UseOutlineMicIcon': boolean;
	'setting_UsePixelShiftingHud': boolean;
	'setting_UserCameraResolution': string;
	'setting_UserCameraRollWhileFlying': boolean;
	'setting_UserCameraSaveMetadata': boolean;
	'setting_UserCameraStreamResolution': string;
	'setting_UserCameraTriggerTakesPhotos': boolean;
	'setting_ViveAdvanced': boolean;
	'setting_VoicesVolume': number;
	'setting_VoiceVolumeEnabled': boolean;
	'setting_WebcamDeviceName': string;
	'setting_WingPersistenceEnabled': boolean;
	'setting_WorldTooltipMode': string;
	'setting_WorldVolume': number;
	'setting_WorldVolumeEnabled': boolean;
	'store': string;
	'subscriptionStore': string;
	'subscriptionType': string;
	'systemMemorySize': number;
	'totalaccessoriesownedcount': number;
	'uiLastMenuOpened': string;
	'uiMainMenu.MainMenuAvatarsSelector.SelectedButton': string;
	'uiMainMenu.MainMenuSocialSelector.SelectedButton': string;
	'uiMainMenuCurrentPage': string;
	'uiMainMenuPageStack': string[];
	'uiQuickMenuCurrentPage': string;
	'uiQuickMenuIsAttachedToHand': boolean;
	'uiQuickMenuIsOnRightHand': boolean;
	'uiQuickMenuPageStack': string[];
	'uiWingLeftCurrentPage': string;
	'uiWingLeftIsOpen': boolean;
	'uiWingLeftPageStack': string[];
	'uiWingRightCurrentPage': string;
	'uiWingRightIsOpen': boolean;
	'uiWingRightPageStack': string[];
	'userIcons': number;
	'vrDeviceModel': string;
	'vrDeviceRefreshRate': number;
	'vrDeviceRenderScale': number;
}

export interface $AmplitudeEventProperties {
	'_lastWorldNumberOfCustomEmojiSeen': number;
	'_lastWorldNumberOfCustomEmojiSent': number;
	'_lastWorldNumberOfDefaultEmojiSeen': number;
	'_lastWorldNumberOfDefaultEmojiSent': number;
	'_lastWorldNumberOfEmojiSeen': number;
	'_lastWorldNumberOfEmojiSent': number;
	'_lastWorldNumberOfExclusiveEmojiSeen': number;
	'_lastWorldNumberOfExclusiveEmojiSent': number;
	'_lastWorldNumberOfPremiumEmojiSeen': number;
	'_lastWorldNumberOfPremiumEmojiSent': number;
	'_lastWorldRadialEmojiMenuOpenCount': number;
	'_lastWorldRadialItemMenuOpenCount': number;
	'_lastWorldRadialMenuOpenCount': number;
	'_lastWorldRadialStickerMenuOpenCount': number;
	'avatarIdsEncountered': string[];
	'instanceType': string;
	'ips_loading_banners_seen_count': number;
	'ips_loading_banners_seen_ids': [];
	'ips_loading_categories_seen': [];
	'ipsBannersClickedCounts': [];
	'ipsBannersClickedIds': [];
	'lastLocationId': string;
	'lastWorld_ips_loading_banners_seen_count': number;
	'lastWorld_ips_loading_banners_seen_ids': [];
	'lastWorld_ips_loading_categories_seen': [];
	'lastworld_looks_changed_count': number;
	'lastworld_prop_interacted_prop_ids': [];
	'lastworld_prop_interactions': number;
	'lastworld_prop_viewed_prop_ids': [];
	'lastWorldAvatarChanges_ChangeMethods': string[];
	'lastWorldAvatarChanges_NewAvatarAuthorIds': string[];
	'lastWorldAvatarChanges_NewAvatarAuthorNames': string[];
	'lastWorldAvatarChanges_NewAvatarIds': string[];
	'lastWorldAvatarChanges_NewAvatarNames': string[];
	'lastWorldAvatarChangesCount': number;
	'lastWorldBatteryLevel': number;
	'lastWorldBatteryLevelChange': number;
	'lastWorldBatteryStatus': string;
	'lastWorldDistanceTraveled': number;
	'lastWorldFallbackChanges_ChangeMethods': [];
	'lastWorldFallbackChanges_NewAvatarAuthorIds': [];
	'lastWorldFallbackChanges_NewAvatarAuthorNames': [];
	'lastWorldFallbackChanges_NewAvatarIds': [];
	'lastWorldFallbackChanges_NewAvatarNames': [];
	'lastWorldFallbackChangesCount': number;
	'lastWorldHadPersistence': boolean;
	'lastWorldId': string;
	'lastWorldImpostorsLoadedCount': number;
	'lastWorldImpostorsLoadedIds': [];
	'lastWorldImpostorsPreviewedIds': [];
	'lastWorldImpostorsPreviewViewedCount': number;
	'lastWorldInstanceDisplayName': string;
	'lastWorldInstanceOccupants': number;
	'lastWorldInstanceType': string;
	'lastWorldIsHome': boolean;
	'lastWorldLegacyDeviceSeen': boolean;
	'lastWorldLegacyInputUsed': boolean;
	'lastWorldMeanTextMessageCharacters': number;
	'lastWorldMicToggleCount': number;
	'lastWorldMinimumAvatarPerformance': string;
	'lastWorldName': string;
	'lastWorldNumberOfItemsReceivedDirectly': number;
	'lastWorldNumberOfItemsReceivedViaPedestal': number;
	'lastWorldNumberOfItemsSharedDirectly': number;
	'lastWorldNumberOfItemsSharedViaPedestal': number;
	'lastWorldNumberOfSharedItemsReported': number;
	'lastWorldNumberOfStickersCreated': number;
	'lastWorldNumberOfStickersPlaced': number;
	'lastWorldNumberOfUsersMet': number;
	'lastWorldNumCameraOpened': number;
	'lastWorldNumDroneOpened': number;
	'lastWorldNumGiftsGivenViaMassGift': number;
	'lastWorldNumMainMenuOpened': number;
	'lastWorldNumMassGiftsLaunched': number;
	'lastWorldNumNearbyPlayersWithFaceTracking': number;
	'lastWorldNumNearbyPlayersWithFBT': number;
	'lastWorldNumNearbyPlayersWithVR': number;
	'lastWorldNumQuickMenuOpened': number;
	'lastWorldNumUsersGiftedViaMassGifting': number;
	'lastWorldNumVideoPlayerErrors': number;
	'lastWorldNumVideoUrlResolutionsFailedForbidden': number;
	'lastWorldNumVideoUrlResolutionsFailedFoundNoUrls': number;
	'lastWorldNumVideoUrlResolutionsFailedInvalidUrl': number;
	'lastWorldNumVideoUrlResolutionsFailedNotAllowed': number;
	'lastWorldNumVideoUrlResolutionsFailedNotFound': number;
	'lastWorldNumVideoUrlResolutionsFailedYouTube': number;
	'lastWorldNumVideoUrlResolutionsTotalAttempted': number;
	'lastWorldNumVideoUrlResolutionsTotalFailed': number;
	'lastWorldNumVideoUrlResolutionsTotalSuccessful': number;
	'lastWorldNumYouTubeVideoErrors': number;
	'lastWorldPercentTimeSpentLoadingAvatars': number;
	'lastWorldPrivateOccupants': number;
	'lastWorldProfilerSamples sample max ABDM Update': number;
	'lastWorldProfilerSamples sample max AC Reset': number;
	'lastWorldProfilerSamples sample max AC Update': number;
	'lastWorldProfilerSamples sample max ACl Anim': number;
	'lastWorldProfilerSamples sample max ACl Anim Copy Layer Weights': number;
	'lastWorldProfilerSamples sample max ACl Anim Copy Params': number;
	'lastWorldProfilerSamples sample max ACl Ext Blend Shapes': number;
	'lastWorldProfilerSamples sample max ACl Scale Sen': number;
	'lastWorldProfilerSamples sample max ACl Target Pos': number;
	'lastWorldProfilerSamples sample max AMg Instantiate': number;
	'lastWorldProfilerSamples sample max AMg Material': number;
	'lastWorldProfilerSamples sample max AMg Shader': number;
	'lastWorldProfilerSamples sample max Av Audio': number;
	'lastWorldProfilerSamples sample max Av Chop': number;
	'lastWorldProfilerSamples sample max Av Cull': number;
	'lastWorldProfilerSamples sample max Av Head Scale': number;
	'lastWorldProfilerSamples sample max Av Limit Particle Systems': number;
	'lastWorldProfilerSamples sample max Av Safety': number;
	'lastWorldProfilerSamples sample max Av Shaders': number;
	'lastWorldProfilerSamples sample max Av Stop Particle Systems': number;
	'lastWorldProfilerSamples sample max Av Visibility': number;
	'lastWorldProfilerSamples sample max E Tick': number;
	'lastWorldProfilerSamples sample max EOS Update': number;
	'lastWorldProfilerSamples sample max EP Update': number;
	'lastWorldProfilerSamples sample max EvL Clear': number;
	'lastWorldProfilerSamples sample max EvL Update': number;
	'lastWorldProfilerSamples sample max EvRp Event': number;
	'lastWorldProfilerSamples sample max EyeAnim Cache': number;
	'lastWorldProfilerSamples sample max FBN Player Order': number;
	'lastWorldProfilerSamples sample max FBN Update': number;
	'lastWorldProfilerSamples sample max Flow Core Ready': number;
	'lastWorldProfilerSamples sample max Flow Is Core': number;
	'lastWorldProfilerSamples sample max GC AllocateMegabytes': number;
	'lastWorldProfilerSamples sample max GC Collect': number;
	'lastWorldProfilerSamples sample max GC EnsureHeapSize': number;
	'lastWorldProfilerSamples sample max HpCm Logic': number;
	'lastWorldProfilerSamples sample max HUD': number;
	'lastWorldProfilerSamples sample max IKC Update': number;
	'lastWorldProfilerSamples sample max MoS Update': number;
	'lastWorldProfilerSamples sample max Net Thread Mgr': number;
	'lastWorldProfilerSamples sample max Networking Book': number;
	'lastWorldProfilerSamples sample max Networking Cache Copy and Elimination': number;
	'lastWorldProfilerSamples sample max Networking Cache Processing': number;
	'lastWorldProfilerSamples sample max Networking Flush': number;
	'lastWorldProfilerSamples sample max Networking Incoming': number;
	'lastWorldProfilerSamples sample max Networking Suffer': number;
	'lastWorldProfilerSamples sample max NP Calc': number;
	'lastWorldProfilerSamples sample max NP Material': number;
	'lastWorldProfilerSamples sample max NP Offset': number;
	'lastWorldProfilerSamples sample max NP Voice': number;
	'lastWorldProfilerSamples sample max OG Update': number;
	'lastWorldProfilerSamples sample max PL Update': number;
	'lastWorldProfilerSamples sample max PNP Update': number;
	'lastWorldProfilerSamples sample max Pose Local Update Position': number;
	'lastWorldProfilerSamples sample max PStS Update': number;
	'lastWorldProfilerSamples sample max Settings Update': number;
	'lastWorldProfilerSamples sample max SimT Update': number;
	'lastWorldProfilerSamples sample max SyncPhys Update': number;
	'lastWorldProfilerSamples sample max USp Get Data': number;
	'lastWorldProfilerSamples sample max USp isPlaying': number;
	'lastWorldProfilerSamples sample max USp recording': number;
	'lastWorldProfilerSamples sample max USp send': number;
	'lastWorldProfilerSamples sample max USp TotalVoiceHeardTime': number;
	'lastWorldProfilerSamples sample max Validation Audio Source Limits': number;
	'lastWorldProfilerSamples sample max Validation Avatar Dynamics Limits': number;
	'lastWorldProfilerSamples sample max Validation Avatar IK Limits': number;
	'lastWorldProfilerSamples sample max Validation Avatar Station Limits': number;
	'lastWorldProfilerSamples sample mean ABDM Update': number;
	'lastWorldProfilerSamples sample mean AC Reset': number;
	'lastWorldProfilerSamples sample mean AC Update': number;
	'lastWorldProfilerSamples sample mean ACl Anim': number;
	'lastWorldProfilerSamples sample mean ACl Anim Copy Layer Weights': number;
	'lastWorldProfilerSamples sample mean ACl Anim Copy Params': number;
	'lastWorldProfilerSamples sample mean ACl Ext Blend Shapes': number;
	'lastWorldProfilerSamples sample mean ACl Scale Sen': number;
	'lastWorldProfilerSamples sample mean ACl Target Pos': number;
	'lastWorldProfilerSamples sample mean AMg Instantiate': number;
	'lastWorldProfilerSamples sample mean AMg Material': number;
	'lastWorldProfilerSamples sample mean AMg Shader': number;
	'lastWorldProfilerSamples sample mean Av Audio': number;
	'lastWorldProfilerSamples sample mean Av Chop': number;
	'lastWorldProfilerSamples sample mean Av Cull': number;
	'lastWorldProfilerSamples sample mean Av Head Scale': number;
	'lastWorldProfilerSamples sample mean Av Limit Particle Systems': number;
	'lastWorldProfilerSamples sample mean Av Safety': number;
	'lastWorldProfilerSamples sample mean Av Shaders': number;
	'lastWorldProfilerSamples sample mean Av Stop Particle Systems': number;
	'lastWorldProfilerSamples sample mean Av Visibility': number;
	'lastWorldProfilerSamples sample mean E Tick': number;
	'lastWorldProfilerSamples sample mean EOS Update': number;
	'lastWorldProfilerSamples sample mean EP Update': number;
	'lastWorldProfilerSamples sample mean EvL Clear': number;
	'lastWorldProfilerSamples sample mean EvL Update': number;
	'lastWorldProfilerSamples sample mean EvRp Event': number;
	'lastWorldProfilerSamples sample mean EyeAnim Cache': number;
	'lastWorldProfilerSamples sample mean FBN Player Order': number;
	'lastWorldProfilerSamples sample mean FBN Update': number;
	'lastWorldProfilerSamples sample mean Flow Core Ready': number;
	'lastWorldProfilerSamples sample mean Flow Is Core': number;
	'lastWorldProfilerSamples sample mean GC AllocateMegabytes': number;
	'lastWorldProfilerSamples sample mean GC Collect': number;
	'lastWorldProfilerSamples sample mean GC EnsureHeapSize': number;
	'lastWorldProfilerSamples sample mean HpCm Logic': number;
	'lastWorldProfilerSamples sample mean HUD': number;
	'lastWorldProfilerSamples sample mean IKC Update': number;
	'lastWorldProfilerSamples sample mean MoS Update': number;
	'lastWorldProfilerSamples sample mean Net Thread Mgr': number;
	'lastWorldProfilerSamples sample mean Networking Book': number;
	'lastWorldProfilerSamples sample mean Networking Cache Copy and Elimination': number;
	'lastWorldProfilerSamples sample mean Networking Cache Processing': number;
	'lastWorldProfilerSamples sample mean Networking Flush': number;
	'lastWorldProfilerSamples sample mean Networking Incoming': number;
	'lastWorldProfilerSamples sample mean Networking Suffer': number;
	'lastWorldProfilerSamples sample mean NP Calc': number;
	'lastWorldProfilerSamples sample mean NP Material': number;
	'lastWorldProfilerSamples sample mean NP Offset': number;
	'lastWorldProfilerSamples sample mean NP Voice': number;
	'lastWorldProfilerSamples sample mean OG Update': number;
	'lastWorldProfilerSamples sample mean PL Update': number;
	'lastWorldProfilerSamples sample mean PNP Update': number;
	'lastWorldProfilerSamples sample mean Pose Local Update Position': number;
	'lastWorldProfilerSamples sample mean PStS Update': number;
	'lastWorldProfilerSamples sample mean Settings Update': number;
	'lastWorldProfilerSamples sample mean SimT Update': number;
	'lastWorldProfilerSamples sample mean SyncPhys Update': number;
	'lastWorldProfilerSamples sample mean USp Get Data': number;
	'lastWorldProfilerSamples sample mean USp isPlaying': number;
	'lastWorldProfilerSamples sample mean USp recording': number;
	'lastWorldProfilerSamples sample mean USp send': number;
	'lastWorldProfilerSamples sample mean USp TotalVoiceHeardTime': number;
	'lastWorldProfilerSamples sample mean Validation Audio Source Limits': number;
	'lastWorldProfilerSamples sample mean Validation Avatar Dynamics Limits': number;
	'lastWorldProfilerSamples sample mean Validation Avatar IK Limits': number;
	'lastWorldProfilerSamples sample mean Validation Avatar Station Limits': number;
	'lastWorldProfilerSamples sample timeWeightedMean ABDM Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean AC Reset': number;
	'lastWorldProfilerSamples sample timeWeightedMean AC Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean ACl Anim': number;
	'lastWorldProfilerSamples sample timeWeightedMean ACl Anim Copy Layer Weights': number;
	'lastWorldProfilerSamples sample timeWeightedMean ACl Anim Copy Params': number;
	'lastWorldProfilerSamples sample timeWeightedMean ACl Ext Blend Shapes': number;
	'lastWorldProfilerSamples sample timeWeightedMean ACl Scale Sen': number;
	'lastWorldProfilerSamples sample timeWeightedMean ACl Target Pos': number;
	'lastWorldProfilerSamples sample timeWeightedMean AMg Instantiate': number;
	'lastWorldProfilerSamples sample timeWeightedMean AMg Material': number;
	'lastWorldProfilerSamples sample timeWeightedMean AMg Shader': number;
	'lastWorldProfilerSamples sample timeWeightedMean Av Audio': number;
	'lastWorldProfilerSamples sample timeWeightedMean Av Chop': number;
	'lastWorldProfilerSamples sample timeWeightedMean Av Cull': number;
	'lastWorldProfilerSamples sample timeWeightedMean Av Head Scale': number;
	'lastWorldProfilerSamples sample timeWeightedMean Av Limit Particle Systems': number;
	'lastWorldProfilerSamples sample timeWeightedMean Av Safety': number;
	'lastWorldProfilerSamples sample timeWeightedMean Av Shaders': number;
	'lastWorldProfilerSamples sample timeWeightedMean Av Stop Particle Systems': number;
	'lastWorldProfilerSamples sample timeWeightedMean Av Visibility': number;
	'lastWorldProfilerSamples sample timeWeightedMean E Tick': number;
	'lastWorldProfilerSamples sample timeWeightedMean EOS Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean EP Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean EvL Clear': number;
	'lastWorldProfilerSamples sample timeWeightedMean EvL Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean EvRp Event': number;
	'lastWorldProfilerSamples sample timeWeightedMean EyeAnim Cache': number;
	'lastWorldProfilerSamples sample timeWeightedMean FBN Player Order': number;
	'lastWorldProfilerSamples sample timeWeightedMean FBN Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean Flow Core Ready': number;
	'lastWorldProfilerSamples sample timeWeightedMean Flow Is Core': number;
	'lastWorldProfilerSamples sample timeWeightedMean GC AllocateMegabytes': number;
	'lastWorldProfilerSamples sample timeWeightedMean GC Collect': number;
	'lastWorldProfilerSamples sample timeWeightedMean GC EnsureHeapSize': number;
	'lastWorldProfilerSamples sample timeWeightedMean HpCm Logic': number;
	'lastWorldProfilerSamples sample timeWeightedMean HUD': number;
	'lastWorldProfilerSamples sample timeWeightedMean IKC Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean MoS Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean Net Thread Mgr': number;
	'lastWorldProfilerSamples sample timeWeightedMean Networking Book': number;
	'lastWorldProfilerSamples sample timeWeightedMean Networking Cache Copy and Elimination': number;
	'lastWorldProfilerSamples sample timeWeightedMean Networking Cache Processing': number;
	'lastWorldProfilerSamples sample timeWeightedMean Networking Flush': number;
	'lastWorldProfilerSamples sample timeWeightedMean Networking Incoming': number;
	'lastWorldProfilerSamples sample timeWeightedMean Networking Suffer': number;
	'lastWorldProfilerSamples sample timeWeightedMean NP Calc': number;
	'lastWorldProfilerSamples sample timeWeightedMean NP Material': number;
	'lastWorldProfilerSamples sample timeWeightedMean NP Offset': number;
	'lastWorldProfilerSamples sample timeWeightedMean NP Voice': number;
	'lastWorldProfilerSamples sample timeWeightedMean OG Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean PL Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean PNP Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean Pose Local Update Position': number;
	'lastWorldProfilerSamples sample timeWeightedMean PStS Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean Settings Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean SimT Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean SyncPhys Update': number;
	'lastWorldProfilerSamples sample timeWeightedMean USp Get Data': number;
	'lastWorldProfilerSamples sample timeWeightedMean USp isPlaying': number;
	'lastWorldProfilerSamples sample timeWeightedMean USp recording': number;
	'lastWorldProfilerSamples sample timeWeightedMean USp send': number;
	'lastWorldProfilerSamples sample timeWeightedMean USp TotalVoiceHeardTime': number;
	'lastWorldProfilerSamples sample timeWeightedMean Validation Audio Source Limits': number;
	'lastWorldProfilerSamples sample timeWeightedMean Validation Avatar Dynamics Limits': number;
	'lastWorldProfilerSamples sample timeWeightedMean Validation Avatar IK Limits': number;
	'lastWorldProfilerSamples sample timeWeightedMean Validation Avatar Station Limits': number;
	'lastWorldPublicOccupants': number;
	'lastWorldRegion': string;
	'lastWorldSDKVersion': string;
	'lastWorldSelfieExpressionActiveDuration': number;
	'lastWorldSelfieExpressionAutoQualityEnabled': boolean;
	'lastWorldSelfieExpressionNumAutoDisabled': number;
	'lastWorldSelfieExpressionNumAutoEnabled': number;
	'lastWorldSelfieExpressionNumAutoQualityDecreased': number;
	'lastWorldSelfieExpressionNumAutoQualityIncreased': number;
	'lastWorldSelfieExpressionQualityLevel': number;
	'lastWorldSelfieExpressionSettingEnabled': boolean;
	'lastWorldStats runningTime': number;
	'lastWorldStats stat max avatar_kind_Blocked': number;
	'lastWorldStats stat max avatar_kind_Custom': number;
	'lastWorldStats stat max avatar_kind_Error': number;
	'lastWorldStats stat max avatar_kind_Fallback': number;
	'lastWorldStats stat max avatar_kind_Filtered': number;
	'lastWorldStats stat max avatar_kind_Impostor': number;
	'lastWorldStats stat max avatar_kind_Loading': number;
	'lastWorldStats stat max avatar_kind_Performance': number;
	'lastWorldStats stat max avatar_kind_Safety': number;
	'lastWorldStats stat max avatar_kind_Substitute': number;
	'lastWorldStats stat max avatar_kind_Undefined': number;
	'lastWorldStats stat max avatar_perf_rating_Excellent': number;
	'lastWorldStats stat max avatar_perf_rating_Good': number;
	'lastWorldStats stat max avatar_perf_rating_Medium': number;
	'lastWorldStats stat max avatar_perf_rating_None': number;
	'lastWorldStats stat max avatar_perf_rating_Poor': number;
	'lastWorldStats stat max avatar_perf_rating_VeryPoor': number;
	'lastWorldStats stat max avatar_proxy': number;
	'lastWorldStats stat max cpu_frame_time': number;
	'lastWorldStats stat max fps': number;
	'lastWorldStats stat max gpu_frame_time': number;
	'lastWorldStats stat max input_latency': number;
	'lastWorldStats stat max memory_managed_used': number;
	'lastWorldStats stat max mutual_player_nameplates_visible': number;
	'lastWorldStats stat max ping': number;
	'lastWorldStats stat max player_count': number;
	'lastWorldStats stat max texture_memory_current': number;
	'lastWorldStats stat max texture_memory_desired': number;
	'lastWorldStats stat max texture_memory_nonstreaming': number;
	'lastWorldStats stat max texture_memory_saved_by_streaming': number;
	'lastWorldStats stat max texture_memory_total': number;
	'lastWorldStats stat max visible_player_count': number;
	'lastWorldStats stat mean avatar_kind_Blocked': number;
	'lastWorldStats stat mean avatar_kind_Custom': number;
	'lastWorldStats stat mean avatar_kind_Error': number;
	'lastWorldStats stat mean avatar_kind_Fallback': number;
	'lastWorldStats stat mean avatar_kind_Filtered': number;
	'lastWorldStats stat mean avatar_kind_Impostor': number;
	'lastWorldStats stat mean avatar_kind_Loading': number;
	'lastWorldStats stat mean avatar_kind_Performance': number;
	'lastWorldStats stat mean avatar_kind_Safety': number;
	'lastWorldStats stat mean avatar_kind_Substitute': number;
	'lastWorldStats stat mean avatar_kind_Undefined': number;
	'lastWorldStats stat mean avatar_perf_rating_Excellent': number;
	'lastWorldStats stat mean avatar_perf_rating_Good': number;
	'lastWorldStats stat mean avatar_perf_rating_Medium': number;
	'lastWorldStats stat mean avatar_perf_rating_None': number;
	'lastWorldStats stat mean avatar_perf_rating_Poor': number;
	'lastWorldStats stat mean avatar_perf_rating_VeryPoor': number;
	'lastWorldStats stat mean avatar_proxy': number;
	'lastWorldStats stat mean cpu_frame_time': number;
	'lastWorldStats stat mean fps': number;
	'lastWorldStats stat mean gpu_frame_time': number;
	'lastWorldStats stat mean input_latency': number;
	'lastWorldStats stat mean memory_managed_used': number;
	'lastWorldStats stat mean mutual_player_nameplates_visible': number;
	'lastWorldStats stat mean ping': number;
	'lastWorldStats stat mean player_count': number;
	'lastWorldStats stat mean texture_memory_current': number;
	'lastWorldStats stat mean texture_memory_desired': number;
	'lastWorldStats stat mean texture_memory_nonstreaming': number;
	'lastWorldStats stat mean texture_memory_saved_by_streaming': number;
	'lastWorldStats stat mean texture_memory_total': number;
	'lastWorldStats stat mean visible_player_count': number;
	'lastWorldStats stat min avatar_kind_Blocked': number;
	'lastWorldStats stat min avatar_kind_Custom': number;
	'lastWorldStats stat min avatar_kind_Error': number;
	'lastWorldStats stat min avatar_kind_Fallback': number;
	'lastWorldStats stat min avatar_kind_Filtered': number;
	'lastWorldStats stat min avatar_kind_Impostor': number;
	'lastWorldStats stat min avatar_kind_Loading': number;
	'lastWorldStats stat min avatar_kind_Performance': number;
	'lastWorldStats stat min avatar_kind_Safety': number;
	'lastWorldStats stat min avatar_kind_Substitute': number;
	'lastWorldStats stat min avatar_kind_Undefined': number;
	'lastWorldStats stat min avatar_perf_rating_Excellent': number;
	'lastWorldStats stat min avatar_perf_rating_Good': number;
	'lastWorldStats stat min avatar_perf_rating_Medium': number;
	'lastWorldStats stat min avatar_perf_rating_None': number;
	'lastWorldStats stat min avatar_perf_rating_Poor': number;
	'lastWorldStats stat min avatar_perf_rating_VeryPoor': number;
	'lastWorldStats stat min avatar_proxy': number;
	'lastWorldStats stat min cpu_frame_time': number;
	'lastWorldStats stat min fps': number;
	'lastWorldStats stat min gpu_frame_time': number;
	'lastWorldStats stat min input_latency': number;
	'lastWorldStats stat min memory_managed_used': number;
	'lastWorldStats stat min ping': number;
	'lastWorldStats stat min texture_memory_current': number;
	'lastWorldStats stat min texture_memory_desired': number;
	'lastWorldStats stat min texture_memory_nonstreaming': number;
	'lastWorldStats stat min texture_memory_saved_by_streaming': number;
	'lastWorldStats stat min texture_memory_total': number;
	'lastWorldStats stat timeWeightedMean cpu_frame_time': number;
	'lastWorldStats stat timeWeightedMean fps': number;
	'lastWorldStats stat timeWeightedMean gpu_frame_time': number;
	'lastWorldStats stat timeWeightedMean input_latency': number;
	'lastWorldStats stat timeWeightedMean memory_managed_used': number;
	'lastWorldStats stat timeWeightedMean mutual_player_nameplates_visible': number;
	'lastWorldStats stat timeWeightedMean net_serialize_byte_count AvatarVariablesController': number;
	'lastWorldStats stat timeWeightedMean net_serialize_byte_count PhyBoneRecorder': number;
	'lastWorldStats stat timeWeightedMean ping': number;
	'lastWorldStats stat timeWeightedMean player_count': number;
	'lastWorldStats stat timeWeightedMean texture_memory_current': number;
	'lastWorldStats stat timeWeightedMean texture_memory_desired': number;
	'lastWorldStats stat timeWeightedMean texture_memory_nonstreaming': number;
	'lastWorldStats stat timeWeightedMean texture_memory_saved_by_streaming': number;
	'lastWorldStats stat timeWeightedMean texture_memory_total': number;
	'lastWorldStats stat timeWeightedMean visible_player_count': number;
	'lastWorldStats stat timeWeightedVariance cpu_frame_time': number;
	'lastWorldStats stat timeWeightedVariance fps': number;
	'lastWorldStats stat timeWeightedVariance gpu_frame_time': number;
	'lastWorldStats stat timeWeightedVariance input_latency': number;
	'lastWorldStats stat timeWeightedVariance memory_managed_used': number;
	'lastWorldStats stat timeWeightedVariance mutual_player_nameplates_visible': number;
	'lastWorldStats stat timeWeightedVariance ping': number;
	'lastWorldStats stat timeWeightedVariance player_count': number;
	'lastWorldStats stat timeWeightedVariance texture_memory_current': number;
	'lastWorldStats stat timeWeightedVariance texture_memory_desired': number;
	'lastWorldStats stat timeWeightedVariance texture_memory_nonstreaming': number;
	'lastWorldStats stat timeWeightedVariance texture_memory_saved_by_streaming': number;
	'lastWorldStats stat timeWeightedVariance texture_memory_total': number;
	'lastWorldStats stat timeWeightedVariance visible_player_count': number;
	'lastWorldStats stat total net_bytes 66': number;
	'lastWorldStats stat total net_bytes avatar_interaction_list': number;
	'lastWorldStats stat total net_bytes content_token': number;
	'lastWorldStats stat total net_bytes executive_action': number;
	'lastWorldStats stat total net_bytes instance_metadata': number;
	'lastWorldStats stat total net_bytes instantiate': number;
	'lastWorldStats stat total net_bytes player_big_serialization': number;
	'lastWorldStats stat total net_bytes player_properties': number;
	'lastWorldStats stat total net_bytes player_serialization': number;
	'lastWorldStats stat total net_bytes restricted_views': number;
	'lastWorldStats stat total net_bytes user_model_update': number;
	'lastWorldStats stat total net_events 66': number;
	'lastWorldStats stat total net_events avatar_interaction_list': number;
	'lastWorldStats stat total net_events content_token': number;
	'lastWorldStats stat total net_events executive_action': number;
	'lastWorldStats stat total net_events instance_metadata': number;
	'lastWorldStats stat total net_events instantiate': number;
	'lastWorldStats stat total net_events player_big_serialization': number;
	'lastWorldStats stat total net_events player_properties': number;
	'lastWorldStats stat total net_events player_serialization': number;
	'lastWorldStats stat total net_events restricted_views': number;
	'lastWorldStats stat total net_events user_model_update': number;
	'lastWorldStats stat total net_serialize_byte_count AvatarVariablesController': number;
	'lastWorldStats stat total net_serialize_byte_count PhyBoneRecorder': number;
	'lastWorldStats stat variance avatar_kind_Blocked': number;
	'lastWorldStats stat variance avatar_kind_Custom': number;
	'lastWorldStats stat variance avatar_kind_Error': number;
	'lastWorldStats stat variance avatar_kind_Fallback': number;
	'lastWorldStats stat variance avatar_kind_Filtered': number;
	'lastWorldStats stat variance avatar_kind_Impostor': number;
	'lastWorldStats stat variance avatar_kind_Loading': number;
	'lastWorldStats stat variance avatar_kind_Performance': number;
	'lastWorldStats stat variance avatar_kind_Safety': number;
	'lastWorldStats stat variance avatar_kind_Substitute': number;
	'lastWorldStats stat variance avatar_kind_Undefined': number;
	'lastWorldStats stat variance avatar_perf_rating_Excellent': number;
	'lastWorldStats stat variance avatar_perf_rating_Good': number;
	'lastWorldStats stat variance avatar_perf_rating_Medium': number;
	'lastWorldStats stat variance avatar_perf_rating_None': number;
	'lastWorldStats stat variance avatar_perf_rating_Poor': number;
	'lastWorldStats stat variance avatar_perf_rating_VeryPoor': number;
	'lastWorldStats stat variance avatar_proxy': number;
	'lastWorldStats stat variance cpu_frame_time': number;
	'lastWorldStats stat variance fps': number;
	'lastWorldStats stat variance gpu_frame_time': number;
	'lastWorldStats stat variance input_latency': number;
	'lastWorldStats stat variance memory_managed_used': number;
	'lastWorldStats stat variance mutual_player_nameplates_visible': number;
	'lastWorldStats stat variance ping': number;
	'lastWorldStats stat variance player_count': number;
	'lastWorldStats stat variance texture_memory_current': number;
	'lastWorldStats stat variance texture_memory_desired': number;
	'lastWorldStats stat variance texture_memory_nonstreaming': number;
	'lastWorldStats stat variance texture_memory_saved_by_streaming': number;
	'lastWorldStats stat variance texture_memory_total': number;
	'lastWorldStats stat variance visible_player_count': number;
	'lastWorldStatusUpdatesCount': number;
	'lastWorldTags_world': string[];
	'lastWorldThirdPersonViewActiveRatio': number;
	'lastWorldThirdPersonViewActiveSeconds': number;
	'lastWorldThirdPersonViewAvailable': boolean;
	'lastWorldThirdPersonViewInactiveSeconds': number;
	'lastWorldThirdPersonViewNumTimesFreeRotatePressed': number;
	'lastWorldThirdPersonViewNumTimesKeybindToggled': number;
	'lastWorldThirdPersonViewNumTimesScrollToggled': number;
	'lastWorldThirdPersonViewNumTimesToggled': number;
	'lastWorldTimeSpentInWorld': number;
	'lastWorldTotalMassGiftPackageCost': number;
	'lastWorldTotalTextMessageCharacters': number;
	'lastWorldTotalTextMessagesSent': number;
	'lastWorldTotalTimeHearingSpeech': number;
	'lastWorldTotalTimeSpeaking': number;
	'lastWorldTotalTimeSpentLoadingAvatars': number;
	'lastWorldUnityVersion': string;
	'lastWorldUsersGiftedViaMassGifting': [];
	'lastWorldUsersWithMutualsEncountered': [];
	'lastWorldViewMutualsMMClicked': number;
	'lastWorldViewMutualsQMClicked': number;
	'locationId': string;
	'position': string;
	'source': string;
	'tags_world': string[];
	'worldId': string;
	'worldName': string;
}

export interface $AmplitudeVersion {
	app_version: string;
	device_id: string;
	device_model: string;
	device_name: string;
	event_id: number;
	event_properties: $AmplitudeEventProperties;
	event_type: string;
	insert_id: number;
	ip: string;
	language: string;
	os_name: string;
	os_version: string;
	platform: string;
	session_id: number;
	user_id: string;
	user_properties: $AmplitudeUserProperties;
}

export type $AmplitudeCache = $AmplitudeVersion[];

export interface $AmplitudeSettings {
	'com.amplitude_previousSessionId': number;
	'com.amplitude_sessionLastActiveTime': number;
	'com.amplitude_userId': string;
}
// **************************** VRCHAT AMPLITUDE CACHE **************************** //
